'use strict';
const mobileToggle=document.querySelector('.mobile-toggle');
const primaryNav=document.getElementById('primary-nav');
function setMobileNav(open){if(!mobileToggle||!primaryNav)return;mobileToggle.setAttribute('aria-expanded',String(open));mobileToggle.setAttribute('aria-label',open?'Close navigation':'Open navigation');primaryNav.classList.toggle('mobile-open',open);}
mobileToggle?.addEventListener('click',()=>setMobileNav(mobileToggle.getAttribute('aria-expanded')!=='true'));
primaryNav?.addEventListener('click',event=>{if(event.target.closest('a'))setMobileNav(false);});
document.querySelectorAll('.nav-disclosure').forEach(item=>item.addEventListener('toggle',()=>{if(item.open)document.querySelectorAll('.nav-disclosure').forEach(other=>{if(other!==item)other.open=false;});}));
document.addEventListener('click',event=>{if(!event.target.closest('.nav-disclosure'))document.querySelectorAll('.nav-disclosure').forEach(item=>item.open=false);});
document.addEventListener('keydown',event=>{if(event.key==='Escape'){document.querySelectorAll('.nav-disclosure').forEach(item=>{if(item.open){item.open=false;item.querySelector('summary').focus();}});if(mobileToggle?.getAttribute('aria-expanded')==='true'){setMobileNav(false);mobileToggle.focus();}}});

const stageData=[
 {kicker:'ACQUIRE / START WITH THE RIGHT FIT',title:'The right technology.\nOn the right terms.',description:'Choose new, refurbished or rental equipment around your workload, budget and growth plans. Get a clear view of the options before you commit.',list:['Workload sizing & configuration','New, refurbished & rental options','A plan for support and eventual refresh'],brands:['ServerStore','Rentr','Refurbr'],cta:'Plan your next purchase',need:'serverstore'},
 {kicker:'DEPLOY / GET READY FOR DAY ONE',title:'Ready for your people.\nBuilt for your workload.',description:'Bring hardware, setup and rollout planning together. From a new office to private compute, put the right technology where your business needs it.',list:['Equipment & configuration planning','Workplace and multi-site rollout','Private cloud & dedicated compute'],brands:['Rentr','Host360','AINextLabs'],cta:'Plan your deployment',need:'rentr'},
 {kicker:'MANAGE / KEEP THE BUSINESS MOVING',title:'Technology that works.\nPeople who stay involved.',description:'Scope maintenance, technical support and infrastructure services around your operations. Keep equipment, support and ownership connected as your business grows.',list:['AMC & preventive maintenance','Technical support & repair','Onsite & facility management scope'],brands:['Troubleshootr','Host360','Rentr'],cta:'Discuss ongoing support',need:'troubleshootr'},
 {kicker:'EXTEND / GET MORE FROM WHAT YOU OWN',title:'More useful life.\nMore considered upgrades.',description:'Add capacity, source replacement parts and assess refurbishment before replacing an entire system. Make the next decision with the whole asset lifecycle in view.',list:['Components, upgrades & spares','Legacy equipment requirements','Refurbishment & redeployment options'],brands:['Maxtone','Refurbr','Troubleshootr'],cta:'Plan your next upgrade',need:'maxtone'},
 {kicker:'RETIRE / CLOSE THE LOOP WITH CARE',title:'Recover the value.\nPlan the next beginning.',description:'Assess end-of-use assets for buyback, refurbishment and recycling. Agree data handling, collection and reporting requirements before your equipment leaves your control.',list:['Asset assessment & buyback options','Data disposition & collection scope','Reuse, refurbishment & responsible recycling'],brands:['Ecotribe','Refurbr'],cta:'Discuss asset recovery',need:'ecotribe'}
];
const stageTabs=[...document.querySelectorAll('[data-stage]')];
function selectStage(index,focus=false){const data=stageData[index];if(!data)return;stageTabs.forEach((tab,i)=>{tab.setAttribute('aria-selected',String(index===i));tab.tabIndex=index===i?0:-1;});if(focus)stageTabs[index].focus();document.getElementById('stage-panel').setAttribute('aria-labelledby',`stage-tab-${index}`);document.getElementById('stage-kicker').textContent=data.kicker;const title=document.getElementById('stage-title');title.replaceChildren();data.title.split('\n').forEach((line,i)=>{if(i)title.append(document.createElement('br'));title.append(document.createTextNode(line));});document.getElementById('stage-description').textContent=data.description;const list=document.getElementById('stage-list');list.replaceChildren(...data.list.map((text,i)=>{const li=document.createElement('li'),num=document.createElement('span');num.textContent=`0${i+1}`;li.append(num,document.createTextNode(text));return li;}));const brands=document.getElementById('stage-brands');brands.replaceChildren();data.brands.forEach((brand,i)=>{if(i){const plus=document.createElement('b');plus.textContent='+';brands.append(plus);}brands.append(document.createTextNode(brand));});const cta=document.getElementById('stage-cta');cta.textContent=data.cta+' ↗';cta.dataset.need=data.need;}
stageTabs.forEach((tab,index)=>{tab.addEventListener('click',()=>selectStage(index));tab.addEventListener('keydown',event=>{let next=index;if(event.key==='ArrowRight')next=(index+1)%stageTabs.length;else if(event.key==='ArrowLeft')next=(index+stageTabs.length-1)%stageTabs.length;else if(event.key==='Home')next=0;else if(event.key==='End')next=stageTabs.length-1;else return;event.preventDefault();selectStage(next,true);});});

const needNames={serverstore:'New IT & infrastructure · ServerStore',rentr:'Rentals & leasing · Rentr',refurbr:'Refurbished IT · Refurbr',host360:'Cloud & hosting · Host360',troubleshootr:'Services & support · Troubleshootr',maxtone:'Components & spares · Maxtone',ecotribe:'Asset recovery & ITAD · Ecotribe',ainextlabs:'Enterprise AI · AINextLabs',advice:'IT lifecycle planning · Comprint'};
const form=document.getElementById('project-form');let briefText='';
function selectedNeed(){return form?.querySelector('[name="need"]:checked')?.value;}
function showEnquiryStep(step){const first=document.getElementById('enquiry-step-one'),second=document.getElementById('enquiry-step-two');first.hidden=step!==1;second.hidden=step!==2;document.getElementById('step-label').textContent=step===1?'01 / YOUR REQUIREMENT':'02 / YOUR PROJECT';document.querySelectorAll('.progress-dots i').forEach((dot,i)=>dot.classList.toggle('active',i<step));if(step===2){document.getElementById('selected-need-label').textContent=needNames[selectedNeed()];second.querySelector('input').focus({preventScroll:true});document.querySelector('.enquiry-box').scrollIntoView({block:'start',behavior:'smooth'});}else form.querySelector('[name="need"]:checked')?.focus({preventScroll:true});}
function preselectNeed(need){if(!form||!Object.hasOwn(needNames,need))return;const radio=[...form.querySelectorAll('[name="need"]')].find(input=>input.value===need);if(radio){radio.checked=true;form.hidden=false;document.getElementById('enquiry-result').hidden=true;showEnquiryStep(1);}}
document.querySelectorAll('[data-need]').forEach(link=>link.addEventListener('click',()=>preselectNeed(link.dataset.need)));
if(form){
 const urlNeed=new URLSearchParams(location.search).get('need');if(urlNeed)preselectNeed(urlNeed);
 // Product pages pass ?product= so the brief starts with the model the visitor was viewing.
 const urlProduct=new URLSearchParams(location.search).get('product')?.trim().slice(0,120);const requirementField=form.elements.namedItem('requirement');if(urlProduct&&requirementField&&!requirementField.value)requirementField.value=`Interested in: ${urlProduct}\nQuantity: \nConfiguration notes: `;
 document.getElementById('enquiry-next').addEventListener('click',()=>{if(!selectedNeed()){form.querySelector('[name="need"]').reportValidity();return;}showEnquiryStep(2);});
 document.getElementById('enquiry-back').addEventListener('click',()=>showEnquiryStep(1));
 form.addEventListener('submit',async event=>{
  event.preventDefault();if(!selectedNeed()){showEnquiryStep(1);return;}if(!form.reportValidity())return;
  const data=new FormData(form);const payload=Object.fromEntries([...data.entries()].map(([key,value])=>[key,String(value).trim()]));
  const invalidText=['name','company'].find(key=>!payload[key]);if(invalidText){const input=form.elements.namedItem(invalidText);input.setCustomValidity('Please enter a value.');input.reportValidity();input.addEventListener('input',()=>input.setCustomValidity(''),{once:true});return;}
  const tracking=new URLSearchParams(location.search);payload.source='comprint-website';payload.page=location.pathname;payload.createdAt=new Date().toISOString();for(const key of ['utm_source','utm_medium','utm_campaign'])if(tracking.has(key))payload[key]=tracking.get(key).slice(0,150);
  briefText=`COMPRINT · IT PROJECT BRIEF\n\nStarting point: ${needNames[payload.need]}\nName: ${payload.name}\nCompany: ${payload.company}\nEmail: ${payload.email}\nPhone: ${payload.phone||'Not provided'}\nTimeline: ${payload.timeline}\nLocations: ${payload.location||'To be discussed'}\n\nRequirement:\n${payload.requirement||'Please help us scope the requirement.'}\n\nContact consent: Yes, for this enquiry.`;
  const config=window.COMPRINT_CONTACT||{};const error=document.getElementById('form-error');error.hidden=true;
  if(config.endpoint){
   const button=document.getElementById('enquiry-submit');button.disabled=true;button.textContent='Sending your enquiry…';
   try{const endpoint=new URL(config.endpoint,location.origin);if(endpoint.origin!==location.origin)throw new Error('Use a same-origin CRM proxy.');const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),signal:AbortSignal.timeout(15000)});if(!response.ok)throw new Error('Unable to submit');const confirmation=await response.json();if(confirmation.accepted!==true)throw new Error('No submission confirmation');document.querySelector('#enquiry-result h3').textContent='Your enquiry is with our team.';document.getElementById('result-message').textContent='Thank you. We’ll use the details you shared to connect you with the right specialists.';document.getElementById('result-footnote').textContent='Your enquiry was submitted successfully. Keep a copy of your brief for your records.';document.getElementById('email-brief').hidden=true;}
   catch{error.textContent='We couldn’t send your enquiry. Your details are still here. Please try again or email sales@comprint.co.in.';error.hidden=false;return;}
   finally{button.disabled=false;button.textContent='Send my enquiry ↗';}
  }
  document.getElementById('brief-preview').textContent=briefText;
  document.getElementById('email-brief').href=`mailto:${config.email||'sales@comprint.co.in'}?subject=${encodeURIComponent('IT enquiry · '+payload.company+' · '+needNames[payload.need])}&body=${encodeURIComponent(briefText)}`;
  form.hidden=true;document.getElementById('enquiry-result').hidden=false;document.getElementById('step-label').textContent=config.endpoint?'ENQUIRY SUBMITTED':'YOUR PROJECT BRIEF';document.getElementById('enquiry-result').setAttribute('tabindex','-1');document.getElementById('enquiry-result').focus({preventScroll:true});document.querySelector('.enquiry-box').scrollIntoView({block:'start',behavior:'smooth'});
 });
 document.getElementById('edit-brief').addEventListener('click',()=>{form.hidden=false;document.getElementById('enquiry-result').hidden=true;showEnquiryStep(2);});
 document.getElementById('download-brief').addEventListener('click',()=>{const blob=new Blob([briefText],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download='comprint-it-project-brief.txt';anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
 if(window.COMPRINT_CONTACT?.endpoint){document.getElementById('enquiry-submit').textContent='Send my enquiry ↗';document.querySelector('#enquiry-step-two .bottom-hint').textContent='We’ll use your details to respond to this enquiry.';}
}
// Existing detailed pages share the same honest email handoff until the CRM proxy is configured.
document.querySelectorAll('form.rfq').forEach(legacy=>{legacy.addEventListener('submit',event=>{event.preventDefault();if(!legacy.reportValidity())return;const lines=[document.title,''];legacy.querySelectorAll('input,select,textarea').forEach(input=>{if(['submit','checkbox','hidden'].includes(input.type))return;const label=legacy.querySelector(`label[for="${input.id}"]`);lines.push(`${label?.textContent||input.name||input.id}: ${input.value}`);});let result=legacy.querySelector('.legacy-form-result');if(!result){result=document.createElement('div');result.className='legacy-form-result';result.setAttribute('role','status');legacy.append(result);}result.replaceChildren();const message=document.createElement('p');message.textContent='Your enquiry is ready. Open your email to review and send it to our team.';const anchor=document.createElement('a');anchor.className='button dark';anchor.textContent='Open email to Comprint ↗';anchor.href=`mailto:sales@comprint.co.in?subject=${encodeURIComponent('Comprint enquiry · '+document.title)}&body=${encodeURIComponent(lines.join('\n'))}`;result.append(message,anchor);});});
